
[phases.setup]
nixPkgs = ['nodejs', 'yarn']

[phases.install]
cmds = ['yarn install --frozen-lockfile']

[phases.build]
cmds = [
  'npx prisma generate',
  'yarn build'
]

[start]
cmd = 'yarn start'
